"""Store all constants needed for other module to access."""

SCREEN_HEIGHT = 600
SCREEN_WIDTH = 1000
BOTTOM_MARGIN = 20

PLAYER_STARTING_POS_Y = -((SCREEN_HEIGHT / 2) - BOTTOM_MARGIN)
PLAYER_STARTING_POS = (0, PLAYER_STARTING_POS_Y)
TRAVERSE = 10
STEP_BACK = -5
