"""Store all constants needed for other module to access."""

SCREEN_HEIGHT = 600
SCREEN_WIDTH = 1000
MARGIN = 20

PLAYER_STARTING_POS_Y = -((SCREEN_HEIGHT / 2) - MARGIN)
PLAYER_STARTING_POS = (0, PLAYER_STARTING_POS_Y)
TRAVERSE = 10
STEP_BACK = -5

SCORE_POS_X = -((SCREEN_WIDTH / 2) - MARGIN)
SCORE_POS_Y = (SCREEN_HEIGHT / 2) - (MARGIN * 2)
FONT = ("Calibri", 14, "bold")
