"""Store all constant used in other modules"""

GAME_NAME = "Pong Game"
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
PADDLE_MARGIN = 30
PADDLE_MOVE_SPEED = 20
BALL_SIZE = 20
DEFAULT_SEGMENT_SIZE = 20

# the ratio is power of 20
PADDLE_WIDTH = 1
PADDLE_HEIGHT = 10

# set the x coordinate of paddle
X_COR = (SCREEN_WIDTH / 2) - PADDLE_MARGIN
Y_COR = (SCREEN_HEIGHT / 2) - (PADDLE_HEIGHT * DEFAULT_SEGMENT_SIZE / 4) - DEFAULT_SEGMENT_SIZE

RANDOM_DIRECTION_POWER = [-1, 1]
BOTTOM_TOP_WALL_Y = (SCREEN_HEIGHT / 2) - BALL_SIZE
